In [387]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [388]:
dataset = pd.read_csv('Data Wisata.csv')
x = dataset.iloc[:,0:2].values

In [389]:
print(x)

[[  2009.  67480.]
 [  2010.  45845.]
 [  2011.     nan]
 [  2012. 179325.]
 [  2013.  81940.]
 [  2014.  27435.]
 [  2015.  78230.]
 [  2016.  36340.]
 [  2017.  84070.]
 [  2018. 112265.]
 [  2019.  73045.]
 [  2020. 122905.]]


In [390]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [391]:
print(x)

[[  2009.          67480.        ]
 [  2010.          45845.        ]
 [  2011.          82625.45454545]
 [  2012.         179325.        ]
 [  2013.          81940.        ]
 [  2014.          27435.        ]
 [  2015.          78230.        ]
 [  2016.          36340.        ]
 [  2017.          84070.        ]
 [  2018.         112265.        ]
 [  2019.          73045.        ]
 [  2020.         122905.        ]]


In [392]:
from sklearn.model_selection import train_test_split
x_train, x_test = train_test_split(x, test_size=0.2)

In [393]:
print(x_train)

[[  2011.          82625.45454545]
 [  2018.         112265.        ]
 [  2013.          81940.        ]
 [  2012.         179325.        ]
 [  2009.          67480.        ]
 [  2014.          27435.        ]
 [  2020.         122905.        ]
 [  2015.          78230.        ]
 [  2010.          45845.        ]]


In [394]:
print(x_test)

[[ 2017. 84070.]
 [ 2019. 73045.]
 [ 2016. 36340.]]
